### Create User
POST http://localhost:8000/register
Content-Type: application/json

{
  "username": "andi",
  "password": "testPassword"
}

### Login
POST http://localhost:8000/login
Content-Type: application/json

{
  "username": "andi",
  "password": "testPassword"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("token", response.body.data.access_token);
    });
%}

### Profile
GET http://localhost:8000/profile
Content-Type: application/json
Authorization: Bearer {{token}}


### Get All Assets
GET http://localhost:8001/assets
Authorization: Bearer {{token}}


### Create Assets
POST http://localhost:8001/assets
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "value": 12.5,
  "name": "Lemari"
}
### Get a Single Asset by ID
GET http://localhost:8001/assets/1
Authorization: Bearer {{token}}